server:
  port: 8080
  servlet:
    context-path: /loan

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  cache:
    type: hazelcast
  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000 # 5 minutes
      connection-timeout: 30000 # 30 seconds
      max-lifetime: 1800000 # 30 minutes
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  pagination:
    default-page: 0
    default-size: 36

jwt:
  secretKey: ${JWT_SECRET_KEY:loan-secret}
  expirationMs: ${JWT_EXPIRATION_MS:600000}
